// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Cluster.
func (mg *Cluster) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ClusterTemplateID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ClusterTemplateIDRef,
		Selector:     mg.Spec.ForProvider.ClusterTemplateIDSelector,
		To: reference.To{
			List:    &ClusterTemplateList{},
			Managed: &ClusterTemplate{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ClusterTemplateID")
	}
	mg.Spec.ForProvider.ClusterTemplateID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ClusterTemplateIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ClusterTemplateID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.ClusterTemplateIDRef,
		Selector:     mg.Spec.InitProvider.ClusterTemplateIDSelector,
		To: reference.To{
			List:    &ClusterTemplateList{},
			Managed: &ClusterTemplate{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ClusterTemplateID")
	}
	mg.Spec.InitProvider.ClusterTemplateID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ClusterTemplateIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this ClusterRoleTemplateBinding.
func (mg *ClusterRoleTemplateBinding) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ClusterID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ClusterIDRef,
		Selector:     mg.Spec.ForProvider.ClusterIDSelector,
		To: reference.To{
			List:    &ClusterV2List{},
			Managed: &ClusterV2{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ClusterID")
	}
	mg.Spec.ForProvider.ClusterID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ClusterIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.RoleTemplateID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.RoleTemplateIDRef,
		Selector:     mg.Spec.ForProvider.RoleTemplateIDSelector,
		To: reference.To{
			List:    &RoleTemplateList{},
			Managed: &RoleTemplate{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.RoleTemplateID")
	}
	mg.Spec.ForProvider.RoleTemplateID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.RoleTemplateIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ClusterID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.ClusterIDRef,
		Selector:     mg.Spec.InitProvider.ClusterIDSelector,
		To: reference.To{
			List:    &ClusterV2List{},
			Managed: &ClusterV2{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ClusterID")
	}
	mg.Spec.InitProvider.ClusterID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ClusterIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.RoleTemplateID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.RoleTemplateIDRef,
		Selector:     mg.Spec.InitProvider.RoleTemplateIDSelector,
		To: reference.To{
			List:    &RoleTemplateList{},
			Managed: &RoleTemplate{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.RoleTemplateID")
	}
	mg.Spec.InitProvider.RoleTemplateID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.RoleTemplateIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this ClusterSync.
func (mg *ClusterSync) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var mrsp reference.MultiResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ClusterID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ClusterIDRef,
		Selector:     mg.Spec.ForProvider.ClusterIDSelector,
		To: reference.To{
			List:    &ClusterV2List{},
			Managed: &ClusterV2{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ClusterID")
	}
	mg.Spec.ForProvider.ClusterID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ClusterIDRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.NodePoolIds),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.ForProvider.NodePoolIdsRefs,
		Selector:      mg.Spec.ForProvider.NodePoolIdsSelector,
		To: reference.To{
			List:    &NodePoolList{},
			Managed: &NodePool{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NodePoolIds")
	}
	mg.Spec.ForProvider.NodePoolIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.NodePoolIdsRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ClusterID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.ClusterIDRef,
		Selector:     mg.Spec.InitProvider.ClusterIDSelector,
		To: reference.To{
			List:    &ClusterV2List{},
			Managed: &ClusterV2{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ClusterID")
	}
	mg.Spec.InitProvider.ClusterID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ClusterIDRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.NodePoolIds),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.InitProvider.NodePoolIdsRefs,
		Selector:      mg.Spec.InitProvider.NodePoolIdsSelector,
		To: reference.To{
			List:    &NodePoolList{},
			Managed: &NodePool{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.NodePoolIds")
	}
	mg.Spec.InitProvider.NodePoolIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.NodePoolIdsRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this CustomUserToken.
func (mg *CustomUserToken) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Username),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.UsernameRef,
		Selector:     mg.Spec.ForProvider.UsernameSelector,
		To: reference.To{
			List:    &UserList{},
			Managed: &User{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Username")
	}
	mg.Spec.ForProvider.Username = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.UsernameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Username),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.UsernameRef,
		Selector:     mg.Spec.InitProvider.UsernameSelector,
		To: reference.To{
			List:    &UserList{},
			Managed: &User{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Username")
	}
	mg.Spec.InitProvider.Username = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.UsernameRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this EtcdBackup.
func (mg *EtcdBackup) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ClusterID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ClusterIDRef,
		Selector:     mg.Spec.ForProvider.ClusterIDSelector,
		To: reference.To{
			List:    &ClusterV2List{},
			Managed: &ClusterV2{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ClusterID")
	}
	mg.Spec.ForProvider.ClusterID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ClusterIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ClusterID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.ClusterIDRef,
		Selector:     mg.Spec.InitProvider.ClusterIDSelector,
		To: reference.To{
			List:    &ClusterV2List{},
			Managed: &ClusterV2{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ClusterID")
	}
	mg.Spec.InitProvider.ClusterID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ClusterIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this GlobalRoleBinding.
func (mg *GlobalRoleBinding) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.GlobalRoleID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.GlobalRoleIDRef,
		Selector:     mg.Spec.ForProvider.GlobalRoleIDSelector,
		To: reference.To{
			List:    &GlobalRoleList{},
			Managed: &GlobalRole{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.GlobalRoleID")
	}
	mg.Spec.ForProvider.GlobalRoleID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.GlobalRoleIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.GlobalRoleID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.GlobalRoleIDRef,
		Selector:     mg.Spec.InitProvider.GlobalRoleIDSelector,
		To: reference.To{
			List:    &GlobalRoleList{},
			Managed: &GlobalRole{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.GlobalRoleID")
	}
	mg.Spec.InitProvider.GlobalRoleID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.GlobalRoleIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this NodePool.
func (mg *NodePool) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ClusterID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ClusterIDRef,
		Selector:     mg.Spec.ForProvider.ClusterIDSelector,
		To: reference.To{
			List:    &ClusterV2List{},
			Managed: &ClusterV2{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ClusterID")
	}
	mg.Spec.ForProvider.ClusterID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ClusterIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NodeTemplateID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.NodeTemplateIDRef,
		Selector:     mg.Spec.ForProvider.NodeTemplateIDSelector,
		To: reference.To{
			List:    &NodeTemplateList{},
			Managed: &NodeTemplate{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NodeTemplateID")
	}
	mg.Spec.ForProvider.NodeTemplateID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NodeTemplateIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ClusterID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.ClusterIDRef,
		Selector:     mg.Spec.InitProvider.ClusterIDSelector,
		To: reference.To{
			List:    &ClusterV2List{},
			Managed: &ClusterV2{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ClusterID")
	}
	mg.Spec.InitProvider.ClusterID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ClusterIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.NodeTemplateID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.NodeTemplateIDRef,
		Selector:     mg.Spec.InitProvider.NodeTemplateIDSelector,
		To: reference.To{
			List:    &NodeTemplateList{},
			Managed: &NodeTemplate{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.NodeTemplateID")
	}
	mg.Spec.InitProvider.NodeTemplateID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NodeTemplateIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this NodeTemplate.
func (mg *NodeTemplate) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CloudCredentialID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.CloudCredentialIDRef,
		Selector:     mg.Spec.ForProvider.CloudCredentialIDSelector,
		To: reference.To{
			List:    &CloudCredentialList{},
			Managed: &CloudCredential{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CloudCredentialID")
	}
	mg.Spec.ForProvider.CloudCredentialID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CloudCredentialIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DriverID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.DriverIDRef,
		Selector:     mg.Spec.ForProvider.DriverIDSelector,
		To: reference.To{
			List:    &NodeDriverList{},
			Managed: &NodeDriver{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DriverID")
	}
	mg.Spec.ForProvider.DriverID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DriverIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CloudCredentialID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.CloudCredentialIDRef,
		Selector:     mg.Spec.InitProvider.CloudCredentialIDSelector,
		To: reference.To{
			List:    &CloudCredentialList{},
			Managed: &CloudCredential{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CloudCredentialID")
	}
	mg.Spec.InitProvider.CloudCredentialID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CloudCredentialIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DriverID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.DriverIDRef,
		Selector:     mg.Spec.InitProvider.DriverIDSelector,
		To: reference.To{
			List:    &NodeDriverList{},
			Managed: &NodeDriver{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DriverID")
	}
	mg.Spec.InitProvider.DriverID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DriverIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Token.
func (mg *Token) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ClusterID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ClusterIDRef,
		Selector:     mg.Spec.ForProvider.ClusterIDSelector,
		To: reference.To{
			List:    &ClusterV2List{},
			Managed: &ClusterV2{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ClusterID")
	}
	mg.Spec.ForProvider.ClusterID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ClusterIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ClusterID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.ClusterIDRef,
		Selector:     mg.Spec.InitProvider.ClusterIDSelector,
		To: reference.To{
			List:    &ClusterV2List{},
			Managed: &ClusterV2{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ClusterID")
	}
	mg.Spec.InitProvider.ClusterID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ClusterIDRef = rsp.ResolvedReference

	return nil
}
