apiVersion: rancher.contrib.crossplane.io/v1alpha1
kind: ClusterSync
metadata:
  annotations:
    meta.upbound.io/example-id: rancher/v1alpha1/clustersync
  labels:
    testing.upbound.io/example-name: foo-custom
  name: foo-custom
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo-custom
    nodePoolIdsRefs:
    - name: foo

---

apiVersion: rancher.contrib.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: rancher/v1alpha1/clustersync
  labels:
    testing.upbound.io/example-name: foo-custom
  name: foo-custom
spec:
  forProvider:
    description: Foo rancher2 custom cluster
    name: foo-custom
    rkeConfig:
    - network:
      - plugin: canal

---

apiVersion: rancher.contrib.crossplane.io/v1alpha1
kind: NodePool
metadata:
  annotations:
    meta.upbound.io/example-id: rancher/v1alpha1/clustersync
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo-custom
    controlPlane: true
    etcd: true
    hostnamePrefix: foo-cluster-0
    name: foo
    nodeTemplateIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    quantity: 3
    worker: true

---

apiVersion: rancher.contrib.crossplane.io/v1alpha1
kind: NodeTemplate
metadata:
  annotations:
    meta.upbound.io/example-id: rancher/v1alpha1/clustersync
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    amazonec2Config:
    - accessKeySecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
      ami: <AMI_ID>
      region: <REGION>
      secretKeySecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
      securityGroup:
      - <AWS_SECURITY_GROUP>
      subnetId: <SUBNET_ID>
      vpcId: <VPC_ID>
      zone: <ZONE>
    description: foo test
    name: foo

---

apiVersion: k8s.contrib.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: rancher/v1alpha1/clustersync
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo-custom
    containerResourceLimit:
    - limitsCpu: 20m
      limitsMemory: 20Mi
      requestsCpu: 1m
      requestsMemory: 1Mi
    description: Terraform namespace acceptance test
    name: foo
    resourceQuota:
    - namespaceDefaultLimit:
      - limitsCpu: 500m
        limitsMemory: 500Mi
        requestsStorage: 1Gi
      projectLimit:
      - limitsCpu: 2000m
        limitsMemory: 2000Mi
        requestsStorage: 2Gi
