apiVersion: rancher.rancher.contrib.crossplane.io/v1alpha1
kind: EtcdBackup
metadata:
  annotations:
    meta.upbound.io/example-id: rancher/v1alpha1/etcdbackup
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    backupConfig:
    - enabled: true
      intervalHours: 20
      retention: 10
      s3BackupConfig:
      - accessKeySecretRef:
          key: example-key
          name: example-secret
          namespace: upbound-system
        bucketName: bucket_name
        endpoint: endpoint
        folder: /folder
        region: region
        secretKeySecretRef:
          key: example-key
          name: example-secret
          namespace: upbound-system
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    filename: <FILENAME>
    name: foo
