// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2//apis/common/v1"
)

type EtcdBackupBackupConfigInitParameters struct {

	// Enable etcd backup (bool)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Interval hours for etcd backup. Default 12 (int)
	IntervalHours *float64 `json:"intervalHours,omitempty" tf:"interval_hours,omitempty"`

	// Retention for etcd backup. Default 6 (int)
	Retention *float64 `json:"retention,omitempty" tf:"retention,omitempty"`

	// S3 config options for etcd backup. Valid for imported and rke clusters. (list maxitems:1)
	S3BackupConfig []EtcdBackupBackupConfigS3BackupConfigInitParameters `json:"s3BackupConfig,omitempty" tf:"s3_backup_config,omitempty"`

	SafeTimestamp *bool `json:"safeTimestamp,omitempty" tf:"safe_timestamp,omitempty"`

	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type EtcdBackupBackupConfigObservation struct {

	// Enable etcd backup (bool)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Interval hours for etcd backup. Default 12 (int)
	IntervalHours *float64 `json:"intervalHours,omitempty" tf:"interval_hours,omitempty"`

	// Retention for etcd backup. Default 6 (int)
	Retention *float64 `json:"retention,omitempty" tf:"retention,omitempty"`

	// S3 config options for etcd backup. Valid for imported and rke clusters. (list maxitems:1)
	S3BackupConfig []EtcdBackupBackupConfigS3BackupConfigObservation `json:"s3BackupConfig,omitempty" tf:"s3_backup_config,omitempty"`

	SafeTimestamp *bool `json:"safeTimestamp,omitempty" tf:"safe_timestamp,omitempty"`

	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type EtcdBackupBackupConfigParameters struct {

	// Enable etcd backup (bool)
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Interval hours for etcd backup. Default 12 (int)
	// +kubebuilder:validation:Optional
	IntervalHours *float64 `json:"intervalHours,omitempty" tf:"interval_hours,omitempty"`

	// Retention for etcd backup. Default 6 (int)
	// +kubebuilder:validation:Optional
	Retention *float64 `json:"retention,omitempty" tf:"retention,omitempty"`

	// S3 config options for etcd backup. Valid for imported and rke clusters. (list maxitems:1)
	// +kubebuilder:validation:Optional
	S3BackupConfig []EtcdBackupBackupConfigS3BackupConfigParameters `json:"s3BackupConfig,omitempty" tf:"s3_backup_config,omitempty"`

	// +kubebuilder:validation:Optional
	SafeTimestamp *bool `json:"safeTimestamp,omitempty" tf:"safe_timestamp,omitempty"`

	// +kubebuilder:validation:Optional
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type EtcdBackupBackupConfigS3BackupConfigInitParameters struct {

	// Access key for S3 service (string)
	AccessKeySecretRef *v1.SecretKeySelector `json:"accessKeySecretRef,omitempty" tf:"-"`

	// Bucket name for S3 service (string)
	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`

	// Base64 encoded custom CA for S3 service. Use filebase64() for encoding file. Available from Rancher v2.2.5 (string)
	CustomCA *string `json:"customCa,omitempty" tf:"custom_ca,omitempty"`

	// Endpoint for S3 service (string)
	Endpoint *string `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// Folder for S3 service. Available from Rancher v2.2.7 (string)
	Folder *string `json:"folder,omitempty" tf:"folder,omitempty"`

	// Region for S3 service (string)
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Secret key for S3 service (string)
	SecretKeySecretRef *v1.SecretKeySelector `json:"secretKeySecretRef,omitempty" tf:"-"`
}

type EtcdBackupBackupConfigS3BackupConfigObservation struct {

	// Bucket name for S3 service (string)
	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`

	// Base64 encoded custom CA for S3 service. Use filebase64() for encoding file. Available from Rancher v2.2.5 (string)
	CustomCA *string `json:"customCa,omitempty" tf:"custom_ca,omitempty"`

	// Endpoint for S3 service (string)
	Endpoint *string `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// Folder for S3 service. Available from Rancher v2.2.7 (string)
	Folder *string `json:"folder,omitempty" tf:"folder,omitempty"`

	// Region for S3 service (string)
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type EtcdBackupBackupConfigS3BackupConfigParameters struct {

	// Access key for S3 service (string)
	// +kubebuilder:validation:Optional
	AccessKeySecretRef *v1.SecretKeySelector `json:"accessKeySecretRef,omitempty" tf:"-"`

	// Bucket name for S3 service (string)
	// +kubebuilder:validation:Optional
	BucketName *string `json:"bucketName" tf:"bucket_name,omitempty"`

	// Base64 encoded custom CA for S3 service. Use filebase64() for encoding file. Available from Rancher v2.2.5 (string)
	// +kubebuilder:validation:Optional
	CustomCA *string `json:"customCa,omitempty" tf:"custom_ca,omitempty"`

	// Endpoint for S3 service (string)
	// +kubebuilder:validation:Optional
	Endpoint *string `json:"endpoint" tf:"endpoint,omitempty"`

	// Folder for S3 service. Available from Rancher v2.2.7 (string)
	// +kubebuilder:validation:Optional
	Folder *string `json:"folder,omitempty" tf:"folder,omitempty"`

	// Region for S3 service (string)
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Secret key for S3 service (string)
	// +kubebuilder:validation:Optional
	SecretKeySecretRef *v1.SecretKeySelector `json:"secretKeySecretRef,omitempty" tf:"-"`
}

type EtcdBackupInitParameters struct {

	// Annotations for Etcd Backup object (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Backup config for etcd backup (list maxitems:1)
	BackupConfig []EtcdBackupBackupConfigInitParameters `json:"backupConfig,omitempty" tf:"backup_config,omitempty"`

	// Cluster ID to config Etcd Backup (string)
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher/apis/rancher/v1alpha1.ClusterV2
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// Filename of the Etcd Backup (string)
	Filename *string `json:"filename,omitempty" tf:"filename,omitempty"`

	// Labels for Etcd Backup object (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Manual execution of the Etcd Backup. Default false (bool)
	Manual *bool `json:"manual,omitempty" tf:"manual,omitempty"`

	// The name of the Etcd Backup (string)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Description for the Etcd Backup (string)
	NamespaceID *string `json:"namespaceId,omitempty" tf:"namespace_id,omitempty"`
}

type EtcdBackupObservation struct {

	// Annotations for Etcd Backup object (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Backup config for etcd backup (list maxitems:1)
	BackupConfig []EtcdBackupBackupConfigObservation `json:"backupConfig,omitempty" tf:"backup_config,omitempty"`

	// Cluster ID to config Etcd Backup (string)
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Filename of the Etcd Backup (string)
	Filename *string `json:"filename,omitempty" tf:"filename,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels for Etcd Backup object (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Manual execution of the Etcd Backup. Default false (bool)
	Manual *bool `json:"manual,omitempty" tf:"manual,omitempty"`

	// The name of the Etcd Backup (string)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Description for the Etcd Backup (string)
	NamespaceID *string `json:"namespaceId,omitempty" tf:"namespace_id,omitempty"`
}

type EtcdBackupParameters struct {

	// Annotations for Etcd Backup object (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Backup config for etcd backup (list maxitems:1)
	// +kubebuilder:validation:Optional
	BackupConfig []EtcdBackupBackupConfigParameters `json:"backupConfig,omitempty" tf:"backup_config,omitempty"`

	// Cluster ID to config Etcd Backup (string)
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher/apis/rancher/v1alpha1.ClusterV2
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// Filename of the Etcd Backup (string)
	// +kubebuilder:validation:Optional
	Filename *string `json:"filename,omitempty" tf:"filename,omitempty"`

	// Labels for Etcd Backup object (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Manual execution of the Etcd Backup. Default false (bool)
	// +kubebuilder:validation:Optional
	Manual *bool `json:"manual,omitempty" tf:"manual,omitempty"`

	// The name of the Etcd Backup (string)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Description for the Etcd Backup (string)
	// +kubebuilder:validation:Optional
	NamespaceID *string `json:"namespaceId,omitempty" tf:"namespace_id,omitempty"`
}

// EtcdBackupSpec defines the desired state of EtcdBackup
type EtcdBackupSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     EtcdBackupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EtcdBackupInitParameters `json:"initProvider,omitempty"`
}

// EtcdBackupStatus defines the observed state of EtcdBackup.
type EtcdBackupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EtcdBackupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// EtcdBackup is the Schema for the EtcdBackups API. |Provides a Rancher v2 Etcd Backup resource. This can be used to create an Etcd Backup for Rancher v2.2.x and above, and to retrieve their information.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rancher}
type EtcdBackup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   EtcdBackupSpec   `json:"spec"`
	Status EtcdBackupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EtcdBackupList contains a list of EtcdBackups
type EtcdBackupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EtcdBackup `json:"items"`
}

// Repository type metadata.
var (
	EtcdBackup_Kind             = "EtcdBackup"
	EtcdBackup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EtcdBackup_Kind}.String()
	EtcdBackup_KindAPIVersion   = EtcdBackup_Kind + "." + CRDGroupVersion.String()
	EtcdBackup_GroupVersionKind = CRDGroupVersion.WithKind(EtcdBackup_Kind)
)

func init() {
	SchemeBuilder.Register(&EtcdBackup{}, &EtcdBackupList{})
}
