// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	"dario.cat/mergo"
	"github.com/pkg/errors"

	"github.com/crossplane/upjet/v2/pkg/resource"
	"github.com/crossplane/upjet/v2/pkg/resource/json"
)

// GetTerraformResourceType returns Terraform resource type for this NodeTemplate
func (mg *NodeTemplate) GetTerraformResourceType() string {
	return "rancher2_node_template"
}

// GetConnectionDetailsMapping for this NodeTemplate
func (tr *NodeTemplate) GetConnectionDetailsMapping() map[string]string {
	return map[string]string{"amazonec2_config[*].access_key": "amazonec2Config[*].accessKeySecretRef", "amazonec2_config[*].secret_key": "amazonec2Config[*].secretKeySecretRef", "amazonec2_config[*].session_token": "amazonec2Config[*].sessionTokenSecretRef", "auth_certificate_authority": "authCertificateAuthoritySecretRef", "auth_key": "authKeySecretRef", "azure_config[*].client_id": "azureConfig[*].clientIdSecretRef", "azure_config[*].client_secret": "azureConfig[*].clientSecretSecretRef", "azure_config[*].subscription_id": "azureConfig[*].subscriptionIdSecretRef", "digitalocean_config[*].access_token": "digitaloceanConfig[*].accessTokenSecretRef", "digitalocean_config[*].ssh_key_fingerprint": "digitaloceanConfig[*].sshKeyFingerprintSecretRef", "harvester_config[*].ssh_password": "harvesterConfig[*].sshPasswordSecretRef", "hetzner_config[*].api_token": "hetznerConfig[*].apiTokenSecretRef", "linode_config[*].root_pass": "linodeConfig[*].rootPassSecretRef", "linode_config[*].token": "linodeConfig[*].tokenSecretRef", "opennebula_config[*].password": "opennebulaConfig[*].passwordSecretRef", "openstack_config[*].application_credential_secret": "openstackConfig[*].applicationCredentialSecretSecretRef", "openstack_config[*].password": "openstackConfig[*].passwordSecretRef", "openstack_config[*].private_key_file": "openstackConfig[*].privateKeyFileSecretRef", "outscale_config[*].access_key": "outscaleConfig[*].accessKeySecretRef", "outscale_config[*].secret_key": "outscaleConfig[*].secretKeySecretRef", "vsphere_config[*].password": "vsphereConfig[*].passwordSecretRef", "vsphere_config[*].ssh_password": "vsphereConfig[*].sshPasswordSecretRef"}
}

// GetObservation of this NodeTemplate
func (tr *NodeTemplate) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this NodeTemplate
func (tr *NodeTemplate) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this NodeTemplate
func (tr *NodeTemplate) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this NodeTemplate
func (tr *NodeTemplate) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this NodeTemplate
func (tr *NodeTemplate) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// GetInitParameters of this NodeTemplate
func (tr *NodeTemplate) GetInitParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.InitProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// GetInitParameters of this NodeTemplate
func (tr *NodeTemplate) GetMergedParameters(shouldMergeInitProvider bool) (map[string]any, error) {
	params, err := tr.GetParameters()
	if err != nil {
		return nil, errors.Wrapf(err, "cannot get parameters for resource '%q'", tr.GetName())
	}
	if !shouldMergeInitProvider {
		return params, nil
	}

	initParams, err := tr.GetInitParameters()
	if err != nil {
		return nil, errors.Wrapf(err, "cannot get init parameters for resource '%q'", tr.GetName())
	}

	// Note(lsviben): mergo.WithSliceDeepCopy is needed to merge the
	// slices from the initProvider to forProvider. As it also sets
	// overwrite to true, we need to set it back to false, we don't
	// want to overwrite the forProvider fields with the initProvider
	// fields.
	err = mergo.Merge(&params, initParams, mergo.WithSliceDeepCopy, func(c *mergo.Config) {
		c.Overwrite = false
	})
	if err != nil {
		return nil, errors.Wrapf(err, "cannot merge spec.initProvider and spec.forProvider parameters for resource '%q'", tr.GetName())
	}

	return params, nil
}

// LateInitialize this NodeTemplate using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *NodeTemplate) LateInitialize(attrs []byte) (bool, error) {
	params := &NodeTemplateParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *NodeTemplate) GetTerraformSchemaVersion() int {
	return 0
}
