// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AppInitParameters struct {

	// Annotations for App object (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Answers for the app template. If modified, app will be upgraded (map)
	// Answers of the app
	// +mapType=granular
	Answers map[string]*string `json:"answers,omitempty" tf:"answers,omitempty"`

	// Catalog name of the app. If modified, app will be upgraded. For use scoped catalogs:
	// Catalog name of the app
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher/apis/app/v1alpha1.Catalog
	CatalogName *string `json:"catalogName,omitempty" tf:"catalog_name,omitempty"`

	// Reference to a Catalog in app to populate catalogName.
	// +kubebuilder:validation:Optional
	CatalogNameRef *v1.Reference `json:"catalogNameRef,omitempty" tf:"-"`

	// Selector for a Catalog in app to populate catalogName.
	// +kubebuilder:validation:Optional
	CatalogNameSelector *v1.Selector `json:"catalogNameSelector,omitempty" tf:"-"`

	// Description for the app (string)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Force app upgrade (string)
	// Force app upgrade
	ForceUpgrade *bool `json:"forceUpgrade,omitempty" tf:"force_upgrade,omitempty"`

	// Labels for App object (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the app (string)
	// Name of the app
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The project id where the app will be installed (string)
	// Project ID to add app
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher/apis/k8s/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in k8s to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in k8s to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// Current revision id for the app. If modified, If this argument is provided or modified, app will be rollbacked to revision_id (string)
	// App revision id
	RevisionID *string `json:"revisionId,omitempty" tf:"revision_id,omitempty"`

	// The namespace id where the app will be installed (string)
	// Namespace name to add app
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher/apis/k8s/v1alpha1.Namespace
	TargetNamespace *string `json:"targetNamespace,omitempty" tf:"target_namespace,omitempty"`

	// Reference to a Namespace in k8s to populate targetNamespace.
	// +kubebuilder:validation:Optional
	TargetNamespaceRef *v1.Reference `json:"targetNamespaceRef,omitempty" tf:"-"`

	// Selector for a Namespace in k8s to populate targetNamespace.
	// +kubebuilder:validation:Optional
	TargetNamespaceSelector *v1.Selector `json:"targetNamespaceSelector,omitempty" tf:"-"`

	// Template name of the app. If modified, app will be upgraded (string)
	// Template name of the app
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`

	// Template version of the app. If modified, app will be upgraded. Default: latest (string)
	// Template version of the app
	TemplateVersion *string `json:"templateVersion,omitempty" tf:"template_version,omitempty"`

	// values.yaml base64 encoded file content for the app template. If modified, app will be upgraded (string)
	// values.yaml base64 encoded file content of the app
	ValuesYaml *string `json:"valuesYaml,omitempty" tf:"values_yaml,omitempty"`

	// Wait until app is deployed and active. Default: true (bool)
	// Wait until app is deployed and active
	Wait *bool `json:"wait,omitempty" tf:"wait,omitempty"`
}

type AppObservation struct {

	// Annotations for App object (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Answers for the app template. If modified, app will be upgraded (map)
	// Answers of the app
	// +mapType=granular
	Answers map[string]*string `json:"answers,omitempty" tf:"answers,omitempty"`

	// Catalog name of the app. If modified, app will be upgraded. For use scoped catalogs:
	// Catalog name of the app
	CatalogName *string `json:"catalogName,omitempty" tf:"catalog_name,omitempty"`

	// Description for the app (string)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Computed) The url of the app template on a catalog (string)
	// External ID of the app
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// Force app upgrade (string)
	// Force app upgrade
	ForceUpgrade *bool `json:"forceUpgrade,omitempty" tf:"force_upgrade,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels for App object (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the app (string)
	// Name of the app
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The project id where the app will be installed (string)
	// Project ID to add app
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Current revision id for the app. If modified, If this argument is provided or modified, app will be rollbacked to revision_id (string)
	// App revision id
	RevisionID *string `json:"revisionId,omitempty" tf:"revision_id,omitempty"`

	// The namespace id where the app will be installed (string)
	// Namespace name to add app
	TargetNamespace *string `json:"targetNamespace,omitempty" tf:"target_namespace,omitempty"`

	// Template name of the app. If modified, app will be upgraded (string)
	// Template name of the app
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`

	// Template version of the app. If modified, app will be upgraded. Default: latest (string)
	// Template version of the app
	TemplateVersion *string `json:"templateVersion,omitempty" tf:"template_version,omitempty"`

	// values.yaml base64 encoded file content for the app template. If modified, app will be upgraded (string)
	// values.yaml base64 encoded file content of the app
	ValuesYaml *string `json:"valuesYaml,omitempty" tf:"values_yaml,omitempty"`

	// Wait until app is deployed and active. Default: true (bool)
	// Wait until app is deployed and active
	Wait *bool `json:"wait,omitempty" tf:"wait,omitempty"`
}

type AppParameters struct {

	// Annotations for App object (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Answers for the app template. If modified, app will be upgraded (map)
	// Answers of the app
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Answers map[string]*string `json:"answers,omitempty" tf:"answers,omitempty"`

	// Catalog name of the app. If modified, app will be upgraded. For use scoped catalogs:
	// Catalog name of the app
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher/apis/app/v1alpha1.Catalog
	// +kubebuilder:validation:Optional
	CatalogName *string `json:"catalogName,omitempty" tf:"catalog_name,omitempty"`

	// Reference to a Catalog in app to populate catalogName.
	// +kubebuilder:validation:Optional
	CatalogNameRef *v1.Reference `json:"catalogNameRef,omitempty" tf:"-"`

	// Selector for a Catalog in app to populate catalogName.
	// +kubebuilder:validation:Optional
	CatalogNameSelector *v1.Selector `json:"catalogNameSelector,omitempty" tf:"-"`

	// Description for the app (string)
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Force app upgrade (string)
	// Force app upgrade
	// +kubebuilder:validation:Optional
	ForceUpgrade *bool `json:"forceUpgrade,omitempty" tf:"force_upgrade,omitempty"`

	// Labels for App object (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the app (string)
	// Name of the app
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The project id where the app will be installed (string)
	// Project ID to add app
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher/apis/k8s/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in k8s to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in k8s to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// Current revision id for the app. If modified, If this argument is provided or modified, app will be rollbacked to revision_id (string)
	// App revision id
	// +kubebuilder:validation:Optional
	RevisionID *string `json:"revisionId,omitempty" tf:"revision_id,omitempty"`

	// The namespace id where the app will be installed (string)
	// Namespace name to add app
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher/apis/k8s/v1alpha1.Namespace
	// +kubebuilder:validation:Optional
	TargetNamespace *string `json:"targetNamespace,omitempty" tf:"target_namespace,omitempty"`

	// Reference to a Namespace in k8s to populate targetNamespace.
	// +kubebuilder:validation:Optional
	TargetNamespaceRef *v1.Reference `json:"targetNamespaceRef,omitempty" tf:"-"`

	// Selector for a Namespace in k8s to populate targetNamespace.
	// +kubebuilder:validation:Optional
	TargetNamespaceSelector *v1.Selector `json:"targetNamespaceSelector,omitempty" tf:"-"`

	// Template name of the app. If modified, app will be upgraded (string)
	// Template name of the app
	// +kubebuilder:validation:Optional
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`

	// Template version of the app. If modified, app will be upgraded. Default: latest (string)
	// Template version of the app
	// +kubebuilder:validation:Optional
	TemplateVersion *string `json:"templateVersion,omitempty" tf:"template_version,omitempty"`

	// values.yaml base64 encoded file content for the app template. If modified, app will be upgraded (string)
	// values.yaml base64 encoded file content of the app
	// +kubebuilder:validation:Optional
	ValuesYaml *string `json:"valuesYaml,omitempty" tf:"values_yaml,omitempty"`

	// Wait until app is deployed and active. Default: true (bool)
	// Wait until app is deployed and active
	// +kubebuilder:validation:Optional
	Wait *bool `json:"wait,omitempty" tf:"wait,omitempty"`
}

// AppSpec defines the desired state of App
type AppSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AppParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AppInitParameters `json:"initProvider,omitempty"`
}

// AppStatus defines the observed state of App.
type AppStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AppObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// App is the Schema for the Apps API. |Provides a Rancher v2 app resource. This can be used to deploy apps within Rancher v2 projects.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rancher}
type App struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.targetNamespace) || (has(self.initProvider) && has(self.initProvider.targetNamespace))",message="spec.forProvider.targetNamespace is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.templateName) || (has(self.initProvider) && has(self.initProvider.templateName))",message="spec.forProvider.templateName is a required parameter"
	Spec   AppSpec   `json:"spec"`
	Status AppStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AppList contains a list of Apps
type AppList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []App `json:"items"`
}

// Repository type metadata.
var (
	App_Kind             = "App"
	App_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: App_Kind}.String()
	App_KindAPIVersion   = App_Kind + "." + CRDGroupVersion.String()
	App_GroupVersionKind = CRDGroupVersion.WithKind(App_Kind)
)

func init() {
	SchemeBuilder.Register(&App{}, &AppList{})
}
