// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type CatalogInitParameters struct {

	// Annotations for the catalog (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The branch of the catalog repo to use. Default master (string)
	Branch *string `json:"branch,omitempty" tf:"branch,omitempty"`

	// The cluster id of the catalog. Mandatory if scope = cluster (string)
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher/apis/rancher/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// A catalog description (string)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The kind of the catalog. Just helm by the moment (string)
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// Labels for the catalog (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the catalog (string)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The password to access the catalog if needed (string)
	PasswordSecretRef *v1.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// The project id of the catalog. Mandatory if scope = project (string)
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher/apis/k8s/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in k8s to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in k8s to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// Catalog will wait for refresh after tf creation and on every tf read. Default false (bool)
	Refresh *bool `json:"refresh,omitempty" tf:"refresh,omitempty"`

	// The scope of the catalog. cluster, global, and project are supported. Default global (string)
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// The url of the catalog repo (string)
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// The username to access the catalog if needed (string)
	UsernameSecretRef *v1.SecretKeySelector `json:"usernameSecretRef,omitempty" tf:"-"`

	// Helm version for the catalog. Available options: helm_v2 and helm_v3 (string)
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type CatalogObservation struct {

	// Annotations for the catalog (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The branch of the catalog repo to use. Default master (string)
	Branch *string `json:"branch,omitempty" tf:"branch,omitempty"`

	// The cluster id of the catalog. Mandatory if scope = cluster (string)
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// A catalog description (string)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The kind of the catalog. Just helm by the moment (string)
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// Labels for the catalog (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the catalog (string)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The project id of the catalog. Mandatory if scope = project (string)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Catalog will wait for refresh after tf creation and on every tf read. Default false (bool)
	Refresh *bool `json:"refresh,omitempty" tf:"refresh,omitempty"`

	// The scope of the catalog. cluster, global, and project are supported. Default global (string)
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// The url of the catalog repo (string)
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Helm version for the catalog. Available options: helm_v2 and helm_v3 (string)
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type CatalogParameters struct {

	// Annotations for the catalog (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The branch of the catalog repo to use. Default master (string)
	// +kubebuilder:validation:Optional
	Branch *string `json:"branch,omitempty" tf:"branch,omitempty"`

	// The cluster id of the catalog. Mandatory if scope = cluster (string)
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher/apis/rancher/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// A catalog description (string)
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The kind of the catalog. Just helm by the moment (string)
	// +kubebuilder:validation:Optional
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// Labels for the catalog (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the catalog (string)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The password to access the catalog if needed (string)
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v1.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// The project id of the catalog. Mandatory if scope = project (string)
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher/apis/k8s/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in k8s to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in k8s to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// Catalog will wait for refresh after tf creation and on every tf read. Default false (bool)
	// +kubebuilder:validation:Optional
	Refresh *bool `json:"refresh,omitempty" tf:"refresh,omitempty"`

	// The scope of the catalog. cluster, global, and project are supported. Default global (string)
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// The url of the catalog repo (string)
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// The username to access the catalog if needed (string)
	// +kubebuilder:validation:Optional
	UsernameSecretRef *v1.SecretKeySelector `json:"usernameSecretRef,omitempty" tf:"-"`

	// Helm version for the catalog. Available options: helm_v2 and helm_v3 (string)
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

// CatalogSpec defines the desired state of Catalog
type CatalogSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CatalogParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CatalogInitParameters `json:"initProvider,omitempty"`
}

// CatalogStatus defines the observed state of Catalog.
type CatalogStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CatalogObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Catalog is the Schema for the Catalogs API. |Provides a Rancher v2 Catalog resource. This can be used to create cluster, global and/or project catalogs for Rancher v2 environments and retrieve their information.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rancher}
type Catalog struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	Spec   CatalogSpec   `json:"spec"`
	Status CatalogStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CatalogList contains a list of Catalogs
type CatalogList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Catalog `json:"items"`
}

// Repository type metadata.
var (
	Catalog_Kind             = "Catalog"
	Catalog_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Catalog_Kind}.String()
	Catalog_KindAPIVersion   = Catalog_Kind + "." + CRDGroupVersion.String()
	Catalog_GroupVersionKind = CRDGroupVersion.WithKind(Catalog_Kind)
)

func init() {
	SchemeBuilder.Register(&Catalog{}, &CatalogList{})
}
