// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AnswersInitParameters struct {

	// Cluster ID for answer (string)
	// Cluster ID for answer
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Project ID for target (string)
	// Project ID for answer
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Key/values for answer (map)
	// Key/values for answer
	// +mapType=granular
	Values map[string]*string `json:"values,omitempty" tf:"values,omitempty"`
}

type AnswersObservation struct {

	// Cluster ID for answer (string)
	// Cluster ID for answer
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Project ID for target (string)
	// Project ID for answer
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Key/values for answer (map)
	// Key/values for answer
	// +mapType=granular
	Values map[string]*string `json:"values,omitempty" tf:"values,omitempty"`
}

type AnswersParameters struct {

	// Cluster ID for answer (string)
	// Cluster ID for answer
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Project ID for target (string)
	// Project ID for answer
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Key/values for answer (map)
	// Key/values for answer
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Values map[string]*string `json:"values,omitempty" tf:"values,omitempty"`
}

type MembersInitParameters struct {

	// Member access type. Valid values: ["member" | "owner" | "read-only"] (string)
	// Member access type: member, owner, read-only
	AccessType *string `json:"accessType,omitempty" tf:"access_type,omitempty"`

	// Member group principal id (string)
	// Member group principal id
	GroupPrincipalID *string `json:"groupPrincipalId,omitempty" tf:"group_principal_id,omitempty"`

	// Member user principal id (string)
	// Member user principal id
	UserPrincipalID *string `json:"userPrincipalId,omitempty" tf:"user_principal_id,omitempty"`
}

type MembersObservation struct {

	// Member access type. Valid values: ["member" | "owner" | "read-only"] (string)
	// Member access type: member, owner, read-only
	AccessType *string `json:"accessType,omitempty" tf:"access_type,omitempty"`

	// Member group principal id (string)
	// Member group principal id
	GroupPrincipalID *string `json:"groupPrincipalId,omitempty" tf:"group_principal_id,omitempty"`

	// Member user principal id (string)
	// Member user principal id
	UserPrincipalID *string `json:"userPrincipalId,omitempty" tf:"user_principal_id,omitempty"`
}

type MembersParameters struct {

	// Member access type. Valid values: ["member" | "owner" | "read-only"] (string)
	// Member access type: member, owner, read-only
	// +kubebuilder:validation:Optional
	AccessType *string `json:"accessType,omitempty" tf:"access_type,omitempty"`

	// Member group principal id (string)
	// Member group principal id
	// +kubebuilder:validation:Optional
	GroupPrincipalID *string `json:"groupPrincipalId,omitempty" tf:"group_principal_id,omitempty"`

	// Member user principal id (string)
	// Member user principal id
	// +kubebuilder:validation:Optional
	UserPrincipalID *string `json:"userPrincipalId,omitempty" tf:"user_principal_id,omitempty"`
}

type MultiClusterAppInitParameters struct {

	// Annotations for multi cluster app object (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The multi cluster app answers (list)
	// Multi cluster app answers
	Answers []AnswersInitParameters `json:"answers,omitempty" tf:"answers,omitempty"`

	// The multi cluster app catalog name (string)
	// Multi cluster app catalog name
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher/apis/app/v1alpha1.CatalogV2
	CatalogName *string `json:"catalogName,omitempty" tf:"catalog_name,omitempty"`

	// Reference to a CatalogV2 in app to populate catalogName.
	// +kubebuilder:validation:Optional
	CatalogNameRef *v1.Reference `json:"catalogNameRef,omitempty" tf:"-"`

	// Selector for a CatalogV2 in app to populate catalogName.
	// +kubebuilder:validation:Optional
	CatalogNameSelector *v1.Selector `json:"catalogNameSelector,omitempty" tf:"-"`

	// Labels for multi cluster app object (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The multi cluster app answers (list)
	// Multi cluster app members
	Members []MembersInitParameters `json:"members,omitempty" tf:"members,omitempty"`

	// The multi cluster app name (string)
	// Multi cluster app name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Computed) The multi cluster app revision history limit. Default 10 (int)
	// Multi cluster app revision history limit
	RevisionHistoryLimit *float64 `json:"revisionHistoryLimit,omitempty" tf:"revision_history_limit,omitempty"`

	// Current revision id for the multi cluster app (string)
	// Multi cluster app revision name
	RevisionID *string `json:"revisionId,omitempty" tf:"revision_id,omitempty"`

	// The multi cluster app roles (list)
	// Multi cluster app roles
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// The multi cluster app target projects (list)
	// Multi cluster app targets
	Targets []TargetsInitParameters `json:"targets,omitempty" tf:"targets,omitempty"`

	// The multi cluster app template name (string)
	// Multi cluster app template name
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`

	// The multi cluster app template version. Default: latest (string)
	// Multi cluster app template version
	TemplateVersion *string `json:"templateVersion,omitempty" tf:"template_version,omitempty"`

	// The multi cluster app upgrade strategy (list MaxItems:1)
	// Multi cluster app upgrade strategy
	UpgradeStrategy []UpgradeStrategyInitParameters `json:"upgradeStrategy,omitempty" tf:"upgrade_strategy,omitempty"`

	// Wait until the multi cluster app is active. Default true (bool)
	// Wait until multi cluster app is active
	Wait *bool `json:"wait,omitempty" tf:"wait,omitempty"`
}

type MultiClusterAppObservation struct {

	// Annotations for multi cluster app object (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The multi cluster app answers (list)
	// Multi cluster app answers
	Answers []AnswersObservation `json:"answers,omitempty" tf:"answers,omitempty"`

	// The multi cluster app catalog name (string)
	// Multi cluster app catalog name
	CatalogName *string `json:"catalogName,omitempty" tf:"catalog_name,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels for multi cluster app object (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The multi cluster app answers (list)
	// Multi cluster app members
	Members []MembersObservation `json:"members,omitempty" tf:"members,omitempty"`

	// The multi cluster app name (string)
	// Multi cluster app name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Computed) The multi cluster app revision history limit. Default 10 (int)
	// Multi cluster app revision history limit
	RevisionHistoryLimit *float64 `json:"revisionHistoryLimit,omitempty" tf:"revision_history_limit,omitempty"`

	// Current revision id for the multi cluster app (string)
	// Multi cluster app revision name
	RevisionID *string `json:"revisionId,omitempty" tf:"revision_id,omitempty"`

	// The multi cluster app roles (list)
	// Multi cluster app roles
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// The multi cluster app target projects (list)
	// Multi cluster app targets
	Targets []TargetsObservation `json:"targets,omitempty" tf:"targets,omitempty"`

	// The multi cluster app template name (string)
	// Multi cluster app template name
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`

	// The multi cluster app template version. Default: latest (string)
	// Multi cluster app template version
	TemplateVersion *string `json:"templateVersion,omitempty" tf:"template_version,omitempty"`

	// (Computed) The multi cluster app template version ID (string)
	// Multi cluster app template version ID
	TemplateVersionID *string `json:"templateVersionId,omitempty" tf:"template_version_id,omitempty"`

	// The multi cluster app upgrade strategy (list MaxItems:1)
	// Multi cluster app upgrade strategy
	UpgradeStrategy []UpgradeStrategyObservation `json:"upgradeStrategy,omitempty" tf:"upgrade_strategy,omitempty"`

	// Wait until the multi cluster app is active. Default true (bool)
	// Wait until multi cluster app is active
	Wait *bool `json:"wait,omitempty" tf:"wait,omitempty"`
}

type MultiClusterAppParameters struct {

	// Annotations for multi cluster app object (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The multi cluster app answers (list)
	// Multi cluster app answers
	// +kubebuilder:validation:Optional
	Answers []AnswersParameters `json:"answers,omitempty" tf:"answers,omitempty"`

	// The multi cluster app catalog name (string)
	// Multi cluster app catalog name
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher/apis/app/v1alpha1.CatalogV2
	// +kubebuilder:validation:Optional
	CatalogName *string `json:"catalogName,omitempty" tf:"catalog_name,omitempty"`

	// Reference to a CatalogV2 in app to populate catalogName.
	// +kubebuilder:validation:Optional
	CatalogNameRef *v1.Reference `json:"catalogNameRef,omitempty" tf:"-"`

	// Selector for a CatalogV2 in app to populate catalogName.
	// +kubebuilder:validation:Optional
	CatalogNameSelector *v1.Selector `json:"catalogNameSelector,omitempty" tf:"-"`

	// Labels for multi cluster app object (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The multi cluster app answers (list)
	// Multi cluster app members
	// +kubebuilder:validation:Optional
	Members []MembersParameters `json:"members,omitempty" tf:"members,omitempty"`

	// The multi cluster app name (string)
	// Multi cluster app name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Computed) The multi cluster app revision history limit. Default 10 (int)
	// Multi cluster app revision history limit
	// +kubebuilder:validation:Optional
	RevisionHistoryLimit *float64 `json:"revisionHistoryLimit,omitempty" tf:"revision_history_limit,omitempty"`

	// Current revision id for the multi cluster app (string)
	// Multi cluster app revision name
	// +kubebuilder:validation:Optional
	RevisionID *string `json:"revisionId,omitempty" tf:"revision_id,omitempty"`

	// The multi cluster app roles (list)
	// Multi cluster app roles
	// +kubebuilder:validation:Optional
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// The multi cluster app target projects (list)
	// Multi cluster app targets
	// +kubebuilder:validation:Optional
	Targets []TargetsParameters `json:"targets,omitempty" tf:"targets,omitempty"`

	// The multi cluster app template name (string)
	// Multi cluster app template name
	// +kubebuilder:validation:Optional
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`

	// The multi cluster app template version. Default: latest (string)
	// Multi cluster app template version
	// +kubebuilder:validation:Optional
	TemplateVersion *string `json:"templateVersion,omitempty" tf:"template_version,omitempty"`

	// The multi cluster app upgrade strategy (list MaxItems:1)
	// Multi cluster app upgrade strategy
	// +kubebuilder:validation:Optional
	UpgradeStrategy []UpgradeStrategyParameters `json:"upgradeStrategy,omitempty" tf:"upgrade_strategy,omitempty"`

	// Wait until the multi cluster app is active. Default true (bool)
	// Wait until multi cluster app is active
	// +kubebuilder:validation:Optional
	Wait *bool `json:"wait,omitempty" tf:"wait,omitempty"`
}

type RollingUpdateInitParameters struct {

	// Rolling update batch size. Default 1 (int)
	// Rolling update batch size
	BatchSize *float64 `json:"batchSize,omitempty" tf:"batch_size,omitempty"`

	// Rolling update interval. Default 1 (int)
	// Rolling update interval
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`
}

type RollingUpdateObservation struct {

	// Rolling update batch size. Default 1 (int)
	// Rolling update batch size
	BatchSize *float64 `json:"batchSize,omitempty" tf:"batch_size,omitempty"`

	// Rolling update interval. Default 1 (int)
	// Rolling update interval
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`
}

type RollingUpdateParameters struct {

	// Rolling update batch size. Default 1 (int)
	// Rolling update batch size
	// +kubebuilder:validation:Optional
	BatchSize *float64 `json:"batchSize,omitempty" tf:"batch_size,omitempty"`

	// Rolling update interval. Default 1 (int)
	// Rolling update interval
	// +kubebuilder:validation:Optional
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`
}

type TargetsInitParameters struct {

	// Project ID for target (string)
	// Project ID for target
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher/apis/k8s/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in k8s to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in k8s to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`
}

type TargetsObservation struct {

	// (Computed) App ID for target (string)
	// App ID for target
	AppID *string `json:"appId,omitempty" tf:"app_id,omitempty"`

	// (Computed) App health state for target (string)
	// App health state for target
	HealthState *string `json:"healthState,omitempty" tf:"health_state,omitempty"`

	// Project ID for target (string)
	// Project ID for target
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Computed) App state for target (string)
	// App state for target
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type TargetsParameters struct {

	// Project ID for target (string)
	// Project ID for target
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher/apis/k8s/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in k8s to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in k8s to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`
}

type UpgradeStrategyInitParameters struct {

	// Upgrade strategy rolling update (list MaxItems:1)
	// Rolling update for upgrade strategy
	RollingUpdate []RollingUpdateInitParameters `json:"rollingUpdate,omitempty" tf:"rolling_update,omitempty"`
}

type UpgradeStrategyObservation struct {

	// Upgrade strategy rolling update (list MaxItems:1)
	// Rolling update for upgrade strategy
	RollingUpdate []RollingUpdateObservation `json:"rollingUpdate,omitempty" tf:"rolling_update,omitempty"`
}

type UpgradeStrategyParameters struct {

	// Upgrade strategy rolling update (list MaxItems:1)
	// Rolling update for upgrade strategy
	// +kubebuilder:validation:Optional
	RollingUpdate []RollingUpdateParameters `json:"rollingUpdate,omitempty" tf:"rolling_update,omitempty"`
}

// MultiClusterAppSpec defines the desired state of MultiClusterApp
type MultiClusterAppSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     MultiClusterAppParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MultiClusterAppInitParameters `json:"initProvider,omitempty"`
}

// MultiClusterAppStatus defines the observed state of MultiClusterApp.
type MultiClusterAppStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MultiClusterAppObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MultiClusterApp is the Schema for the MultiClusterApps API. |Provides a Rancher v2 multi_cluster_app resource. This can be used to deploy multi_cluster_app on Rancher v2.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rancher}
type MultiClusterApp struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.catalogName) || (has(self.initProvider) && has(self.initProvider.catalogName))",message="spec.forProvider.catalogName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.roles) || (has(self.initProvider) && has(self.initProvider.roles))",message="spec.forProvider.roles is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.targets) || (has(self.initProvider) && has(self.initProvider.targets))",message="spec.forProvider.targets is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.templateName) || (has(self.initProvider) && has(self.initProvider.templateName))",message="spec.forProvider.templateName is a required parameter"
	Spec   MultiClusterAppSpec   `json:"spec"`
	Status MultiClusterAppStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MultiClusterAppList contains a list of MultiClusterApps
type MultiClusterAppList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MultiClusterApp `json:"items"`
}

// Repository type metadata.
var (
	MultiClusterApp_Kind             = "MultiClusterApp"
	MultiClusterApp_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MultiClusterApp_Kind}.String()
	MultiClusterApp_KindAPIVersion   = MultiClusterApp_Kind + "." + CRDGroupVersion.String()
	MultiClusterApp_GroupVersionKind = CRDGroupVersion.WithKind(MultiClusterApp_Kind)
)

func init() {
	SchemeBuilder.Register(&MultiClusterApp{}, &MultiClusterAppList{})
}
