apiVersion: v1
kind: Secret
metadata:
  name: example-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "api_url": "https://rancher.webcenter.fr",
      "token_key": "token-d5568:4zh7rrkswnm8zwsd669pht44g7jjsmz5s2ft77qpvxttgvg8jzx8ts"
    }
