apiVersion: project.contrib.crossplane.io/v1alpha1
kind: Project
metadata:
  name: acc-test
spec:
  forProvider:
    name: acc-test
    clusterId: c-m-gj95fddr
    containerResourceLimit:
    - limitsCpu: 20m
      limitsMemory: 20Mi
      requestsCpu: 1m
      requestsMemory: 1Mi
    resourceQuota:
    - namespaceDefaultLimit:
      - limitsCpu: 2000m
        limitsMemory: 500Mi
        requestsStorage: 1Gi
      projectLimit:
      - limitsCpu: 2000m
        limitsMemory: 2000Mi
        requestsStorage: 2Gi
